In [2]:
import arcpy
from arcpy.sa import *
from arcpy import env

env.workspace = r"C:\courses\spa\Week8\Raster_Python\USA_Data.gdb"

hiprecip = Con("average_summer_precip",1,0,"Value > 140")
hitemp = Con("averge_summer_temperature",1,0,"Value > 265")

hotpwet = hiprecip + hitemp 

out_raster = Con(hotpwet,1,0,"Value = 2")

out_raster.save(r"hotandhumid")

In [3]:
import arcpy
from arcpy.sa import *
from arcpy import env

env.workspace = r"C:\courses\spa\Week8\Raster_Python\USA_Data.gdb"

out_raster = Con((Con("average_summer_precip",1,0,"Value > 140") + Con("averge_summer_temperature",1,0,"Value > 265")),1,0,"Value = 2")

out_raster.save(r"hotandhumid2")

In [4]:
import arcpy
from arcpy.sa import *
from arcpy import env

env.workspace = r"C:\courses\spa\Week8\Raster_Python\USA_Data.gdb"

#out_raster = RasterCalculator('"averge_summer_temperature" + "averge_winter_temperature"')
out_raster = Raster("averge_summer_temperature") + Raster("averge_winter_temperature") / 2

out_raster.save(r"averageTemp")

In [5]:
import arcpy
from arcpy.sa import *
from arcpy import env

env.workspace = r"C:\courses\spa\Week8\Raster_Python\USA_Data.gdb"

highslopes = Con(Slope("elevation"),1,0, "Value > 20")

highslopes.save(r"highslopes")

In [9]:
import arcpy
from arcpy import env
from arcpy.sa import *
import numpy as np

arcpy.env.overwriteOutput = True

env.workspace = r"G:\courses\spa\Week8\Raster_Python\USA_Data.gdb"

tempRaster = arcpy.Raster("averge_summer_temperature")

lowerLeft = arcpy.Point(tempRaster.extent.XMin-10000, tempRaster.extent.YMin-1000)
cs = tempRaster.meanCellWidth

arr = arcpy.RasterToNumPyArray(tempRaster, nodata_to_value=-1000)

arr2 = ((arr / 10.0) * (9.0/5.0) + 32.0).astype(int)

Temp_F = arcpy.NumPyArrayToRaster(arr2, lower_left_corner=lowerLeft, x_cell_size=cs, y_cell_size=cs, value_to_nodata=-148)

#Temp_F = arcpy.NumPyArrayToRaster(arr2, lower_left_corner=lowerLeft, x_cell_size=cs-100, y_cell_size=cs-100, value_to_nodata=-148)
#Temp_F.save("ast_wrong")

print(arr2)


[[-148 -148 -148 ...   55   55   55]
 [-148 -148 -148 ...   55   55   55]
 [-148 -148 -148 ...   55   55   55]
 ...
 [-148 -148 -148 ...   80   80   80]
 [-148 -148 -148 ...   80   80   80]
 [-148 -148 -148 ...   80   80 -148]]
