<h3>The function below is a single function that finds the location of any address wordwide.</h3>

In [66]:
import math, urllib
import urllib.parse
import urllib.request
import numpy as np

def getaddresslocation(address, outSR=4326):
    params = urllib.parse.urlencode({'SingleLine': address, 'f': 'json', 'outSR': outSR})
    f = urllib.request.urlopen("https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates?%s" % params)
    loc = eval(f.read())
    outdic = loc['candidates'][0]['location']
    outdic['location'] = address
    return (loc['candidates'][0]['location'])

HBurgLoc = (getaddresslocation("Hattiesburg, MS"))
print(getaddresslocation("Jackson, MS"))
print(getaddresslocation("Los Angeles, CA"))

{'x': -90.18044999999995, 'y': 32.29887000000008, 'location': 'Jackson, MS'}
{'x': -118.24549999999999, 'y': 34.05361000000005, 'location': 'Los Angeles, CA'}


In [67]:
HBurgLoc

{'x': -89.29070999999999, 'y': 31.327350000000024, 'location': 'Hattiesburg, MS'}

In [68]:
getaddresslocation("Long Beach, MS")

{'x': -89.14783999999997, 'y': 30.35451000000006, 'location': 'Long Beach, MS'}

In [71]:
#All the values in the HBurgLoc Dictionary printed as a tuple
HBurgLoc['location'], HBurgLoc['x'], HBurgLoc['y']

('Hattiesburg, MS', -89.29070999999999, 31.327350000000024)

In [94]:
#open a file
f = open(r"G:\courses\spa\W4\Presidents.csv", "r")

outputList = []

for line in f:
    ls = line.split(",")
    result = getaddresslocation(ls[1] + "," + ls[2])
    outputList.append((ls[0], ls[1], ls[2].strip(), result['x'], result['y']))
    

f.close()
del outputList[0]
print(outputList)


[('George Washington', 'Westmoreland County', 'Virginia', -76.80137836199998, 38.111459833000026), ('John Adams', 'Braintree', 'Massachusetts', -70.98898999999994, 42.21282000000008), ('Thomas Jefferson', 'Shadwell', 'Virginia', -78.39934999999997, 38.015550000000076), ('James Madison', 'Port Conway', 'Virginia', -77.18587999999994, 38.17770000000007), ('James Monroe', 'Monroe Hall', 'Virginia', -76.99146999999994, 38.24072000000007), ('Andrew Jackson', 'Waxhaws Region', 'South Carolina', -81.29699451075308, 34.11529859823612), ('John Quincy Adams', 'Braintree', 'Massachusetts', -70.98898999999994, 42.21282000000008), ('William Henry Harrison', 'Charles City County', 'Virginia', -77.05857373799995, 37.354146300000025), ('Martin Van Buren', 'Kinderhook', 'New York', -73.69842999999997, 42.395260000000064), ('Zachary Taylor', 'Barboursville', 'Virginia', -78.27934999999997, 38.17107000000004), ('John Tyler', 'Charles City County', 'Virginia', -77.05857373799995, 37.354146300000025), ('Ja

In [96]:
datadef = [('Name', "S32"),('City', 'S32'),('State', 'S32'), ('X', 'f8'), ('Y', 'f8')]

presidentArray = np.zeros((len(outputList)), dtype=datadef)
presidentArray[:] = outputList[:]
print(presidentArray)

[(b'George Washington', b'Westmoreland County', b'Virginia',  -76.80137836, 38.11145983)
 (b'John Adams', b'Braintree', b'Massachusetts',  -70.98899   , 42.21282   )
 (b'Thomas Jefferson', b'Shadwell', b'Virginia',  -78.39935   , 38.01555   )
 (b'James Madison', b'Port Conway', b'Virginia',  -77.18588   , 38.1777    )
 (b'James Monroe', b'Monroe Hall', b'Virginia',  -76.99147   , 38.24072   )
 (b'Andrew Jackson', b'Waxhaws Region', b'South Carolina',  -81.29699451, 34.1152986 )
 (b'John Quincy Adams', b'Braintree', b'Massachusetts',  -70.98899   , 42.21282   )
 (b'William Henry Harrison', b'Charles City County', b'Virginia',  -77.05857374, 37.3541463 )
 (b'Martin Van Buren', b'Kinderhook', b'New York',  -73.69843   , 42.39526   )
 (b'Zachary Taylor', b'Barboursville', b'Virginia',  -78.27935   , 38.17107   )
 (b'John Tyler', b'Charles City County', b'Virginia',  -77.05857374, 37.3541463 )
 (b'James Buchanan', b'Cove Gap', b'Pennsylvania',  -77.94569   , 39.86649   )
 (b'James K. Polk',

In [102]:
presidentArray["X"].mean(), presidentArray["Y"].mean()

(-82.52614801375312, 38.86392744295017)

In [103]:
presidentArray["X"][-10:].mean(), presidentArray["Y"][-10].mean()

(-91.42128499999997, 33.89152000000007)

In [105]:
np.where(presidentArray["X"] < -89)

(array([29, 31, 32, 33, 34, 35, 36, 41, 42], dtype=int64),)

In [106]:
ind = np.where(presidentArray["X"] < -89)
presidentArray[ind]

array([(b'Herbert Hoover', b'West Branch', b'Iowa',  -91.34663, 41.67244),
       (b'Harry S. Truman', b'Lamar', b'Missouri',  -94.27544, 37.49322),
       (b'Dwight D. Eisenhower', b'Denison', b'Texas',  -96.53662, 33.76038),
       (b'Lyndon B. Johnson', b'Stonewall', b'Texas',  -98.67012, 30.23604),
       (b'Ronald Reagan', b'Tampico', b'Illinois',  -89.78341, 41.6277 ),
       (b'Richard Nixon', b'Yorba Linda', b'California', -117.82432, 33.89152),
       (b'Gerald Ford', b'Omaha', b'Nebraska',  -95.94026, 41.26068),
       (b'Bill Clinton', b'Hope', b'Arkansas',  -93.58985, 33.66742),
       (b'Barack Obama', b'Honolulu', b'Hawaii', -157.85788, 21.30493)],
      dtype=[('Name', 'S32'), ('City', 'S32'), ('State', 'S32'), ('X', '<f8'), ('Y', '<f8')])

In [ ]:
ls[2] = ls[2].strip()

In [79]:
ls[2]

'Pennsylvania'

In [82]:
getaddresslocation(ls[1] + "," + ls[2])

{'x': -75.66077999999999, 'y': 41.410150000000044, 'location': 'Scranton,Pennsylvania'}

In [85]:
outputList[3]

{'x': -78.39934999999997, 'y': 38.015550000000076, 'location': 'Shadwell,Virginia\n'}

[('George Washington', 'Westmoreland County', 'Virginia', -76.80137836199998, 38.111459833000026), ('John Adams', 'Braintree', 'Massachusetts', -70.98898999999994, 42.21282000000008), ('Thomas Jefferson', 'Shadwell', 'Virginia', -78.39934999999997, 38.015550000000076), ('James Madison', 'Port Conway', 'Virginia', -77.18587999999994, 38.17770000000007), ('James Monroe', 'Monroe Hall', 'Virginia', -76.99146999999994, 38.24072000000007), ('Andrew Jackson', 'Waxhaws Region', 'South Carolina', -81.29699451075308, 34.11529859823612), ('John Quincy Adams', 'Braintree', 'Massachusetts', -70.98898999999994, 42.21282000000008), ('William Henry Harrison', 'Charles City County', 'Virginia', -77.05857373799995, 37.354146300000025), ('Martin Van Buren', 'Kinderhook', 'New York', -73.69842999999997, 42.395260000000064), ('Zachary Taylor', 'Barboursville', 'Virginia', -78.27934999999997, 38.17107000000004), ('John Tyler', 'Charles City County', 'Virginia', -77.05857373799995, 37.354146300000025), ('Ja

In [109]:
outputList

sumX = 0

for president in outputList:
    sumX = sumX + president[3]
    
averageX = sumX / len(outputList)
print(averageX)
    

-82.5261480137531


In [111]:
np.median((4,6,7,10))

6.5

In [112]:
xvals = np.array([1,2,3,4])
xmean = xvals.mean()
xmean

2.5

In [113]:
xvalsDiff = xvals - xmean
xvalsDiff

array([-1.5, -0.5,  0.5,  1.5])

In [116]:
xvdSQ = xvalsDiff ** 2
xvdSQ

array([2.25, 0.25, 0.25, 2.25])

In [117]:
xmError = xvdSQ.mean()
xmError

1.25